### PR TITLE
Versions update

### PR DESCRIPTION
**Pull request by cquiroz**
This PR updates the code to be able to work with Play 2.5.3 and use streams from scalaz-stream 0.8a

I tested this converting a scalaz stream to a source for WebSockets under play

All tests are passing

### CODE REVIEW

**Comment by krasserm** [comment]
@cquiroz thanks you very much for the update. Does anything speak against using the latest Akka 2.4.4?

**Comment by cquiroz** [comment]
Do you think this could be merged and released?

**Comment by krasserm** [comment]
Of course I'd like to merge and release, just wanted to know why you didn't upgrade to the latest Akka release (see my previous comment), meanwhile Akka 2.4.6?

**Comment by cquiroz** [comment]
My use case is with play framework and the latest version used at the time was 2.4.2. I'll be happy to update the port to the very latest akka

**Comment by krasserm** [comment]
@cquiroz great, and please squash your commits into a single commit, thanks!

**Comment by cquiroz** [comment]
@krasserm Updated to 2.4.6 as suggested and squashed. I updated scala to 2.11.8 to avoid an eviction warning as akka 2.4.6 depends on scala 2.11.8. All tests are passing

**Comment by krasserm** [comment]
Thanks a lot @cquiroz. Will merge and release later this week.

**Pull request merged**
